pytest test_actions.py -xv && \
pytest test_bash_actions.py -xv && \
pytest test_config.py -xv && \
pytest test_convert.py -xv && \
pytest test_dag.py -xv && \
pytest test_docker_actions.py -xv && \
pytest test_execute.py -xv && \
pytest test_execute_2.py -xv && \
pytest test_julia_action.py -xv && \
pytest test_matlab_action.py -xv && \
pytest test_nested.py -xv && \
pytest test_node_actions.py -xv && \
pytest test_octave_action.py -xv && \
pytest test_outcome.py -xv && \
pytest test_parser.py -xv && \
pytest test_python2_actions.py -xv && \
python test_python3_actions.py -xv && \
pytest test_python3_target.py -xv && \
pytest test_r_actions.py -xv && \
pytest test_r_targets.py -xv && \
pytest test_remote.py -xv && \
pytest test_remove.py -xv && \
pytest test_ruby_actions.py -xv && \
pytest test_singularity.py -xv && \
pytest test_signature.py -xv && \
pytest test_target.py -xv && \
pytest test_task.py -xv && \
pytest test_utils.py -xv
